### PR TITLE
return y_adv

### PR DESCRIPTION
**Pull request by MariaMsu**
I consider that adversarial labels are useful (For example I print them in my visualisations). And Auto-attack compute the labels but does not return the result to the outside. It would be not effective to compute the labels again by hand after Auto-attack returns the images. So I made a change to get the labels directly from the tool

### CODE REVIEW

**Comment by fra31** [comment]
Hi,

thanks for the contribution! I think it makes sense, but I'd leave returning the labels as optional, especially for backward compatibility. What about adding a flag `return_labels`, with default value `False`, to `run_standard_evaluation` arguments, and then
```python
if not return_labels:
    return x_adv
else:
    return x_adv, y_adv
```
and similarly for the individual evaluation?

**Comment by MariaMsu** [comment]
Ok. I will add the flag )

**Comment by MariaMsu** [comment]
Ok, I will add the flag)

**Comment by MariaMsu** [comment]
Not as elegant as I would like. But it works

**Comment by fra31** [comment]
Sorry for the long delay. Thanks again for the contribution!

**Pull request merged**
