### PR TITLE
Unify FAB attack

### PR DESCRIPTION
**Pull request by CNOCycle**
1. framework-independent components in FAB attack are collected in class `FABATTACK`.

2. Pytorch specific functions and TF2 specific functions are implemented in class `FABAttack_PT` and `FABAttack_TF` respectively.

3. The major benefit of this PR is source code is unified. We only need to maintain a copy.

Additionally, I would suggest that `autoattack.fab_projections` should be class `FABATTACK`'s member functions.

### CODE REVIEW

**Comment by fra31** [comment]
This makes a lot of sense, thanks! I'll do something similar for APGD, since anyway I wanted to update its implementation: this indeed would simplify maintaining the code. I'll have a more detailed look and merge.

About moving the projections to `FABATTACK` class, is there a particular benefit in that, or is it about clarity of the code?

**Comment by CNOCycle** [comment]
> About moving the projections to FABATTACK class, is there a particular benefit in that, or is it about clarity of the code?

I guess that the original authors did not want to maintain two copies. So they created a new file `fab_projections.py` which is imported by `fab_tf` and `fab_pt`. However, I have solved this issue in this PR. In my opinion, `projections` are the private functions which are only used by fab attack. Therefore, those functions should be member functions.

**Comment by fra31** [comment]
I see. Then it's fine for me to move them.

**Comment by CNOCycle** [comment]
I am planning to simplify `non-targeted` and `targeted` version attacks.

I fond that function `attack_single_run_targeted` is slightly different from others implementation(function `attack_single_run` in `PT` and `TF` and function attack_single_run_targeted in `PT`).
```diff
--- auto-attack/autoattack/fab_pt.py: function attack_single_run
+++ auto-attack/autoattack/fab_tf.py: function attack_single_run_targeted
            counter_iter = 0
            while counter_iter < self.n_iter:
                with torch.no_grad():
                    df, dg = self.get_diff_logits_grads_batch_targeted(x1, la2, la_target2)
+                    if len(df.shape) == 1:
+                        df.unsqueeze_(1)
+                        dg.unsqueeze_(1)
```
Which implementation should I use ?

**Comment by fra31** [comment]
I'd have to check how it behaves after the new modifications, but originally the `unsqueeze` was used because for the untargeted version the dimension of `df` was `n_classes x batch_size`, but for the targeted one it got squeezed since only one target class is used (and similarly for `dg`). Then it depends on the shape the `df` and `dg`, which is expected to have number of classes or 1 for the targeted version as first entry.

**Comment by CNOCycle** [comment]
OK, I think that I can do reshape in tf side first. So the output tensor's shape in TF and PT are consistent.

**Comment by fra31** [comment]
The new implementation looks indeed much cleaner, thanks!

**Pull request merged**
